vamos_buffers_LIBRARIES_DIRS_core="/home/ouldouz/ISTA/TASK 0/vamos/vamos-buffers/src/core"
vamos_buffers_LIBRARIES_DIRS_shmbuf="/home/ouldouz/ISTA/TASK 0/vamos/vamos-buffers/src/shmbuf"
vamos_buffers_LIBRARIES_DIRS_streams="/home/ouldouz/ISTA/TASK 0/vamos/vamos-buffers/src/streams"
vamos_buffers_INCLUDE_DIR="/home/ouldouz/ISTA/TASK 0/vamos/vamos-buffers/cmake/vamos-buffers/../../include"
vamos_buffers_BUILD_TYPE="RelWithDebInfo"
